changes to the update server, allow to use a single update server

diff --git a/update_server/setup.template b/update_server/setup.template
--- a/update_server/setup.template
+++ b/update_server/setup.template
@@ -20,16 +20,37 @@ echo '
   set -e
   . ~/.nvm/nvm.sh
   export HOME=/root
-  . /etc/profile
   rm -rf /repo
-  git clone https://$GITHUB_USER:$GITHUB_TOKEN@github.com/<%= repo %> /repo
+  git clone https://$GITHUB_USER:$GITHUB_TOKEN@github.com/$REPO /repo
   cd /repo
   npm install && npm install interactive-landscape@latest && cp ./node_modules/interactive-landscape/.nvmrc . && nvm install `cat .nvmrc` && nvm use && npm install -g npm && npm install && npm install interactive-landscape@latest && (export PROJECT_PATH="$PWD"; npm explore interactive-landscape -- npm run update) && npm explore interactive-landscape -- npm run check-links && git add . && git config --global user.email "info@cncf.io" && git config --global user.name "CNCF-bot" && git commit -m "Automated update by CNCF-bot" && git push origin HEAD
 ' > /root/real_update.sh
 echo '
   set -e
-  (bash /root/real_update.sh || bash /root/real_update.sh || bash root/real_update.sh) > /root/update.log
-  cd /repo/node_modules/interactive-landscape && ERROR_STATUS=$? LOGFILE_PATH=/root/update.log ./node_modules/.bin/babel-node tools/reportToSlack.js
-' > /root/update.sh
+  for f in *.settings; do
+    (
+      source "$f"
+      source "$f.private"
+      (bash /root/real_update.sh || bash /root/real_update.sh || bash root/real_update.sh) > /root/update.log
+      cd /repo/node_modules/interactive-landscape && ERROR_STATUS=$? LOGFILE_PATH=/root/update.log ./node_modules/.bin/babel-node tools/reportToSlack.js
+    ) || echo "failed to update a project $f"
+  done
+  ' > /root/update.sh
+echo '
+  export REPO=<%= repo %>
+' > "<%= name %>.settings"
+ls "<%= name %>.settings.private" 2>/dev/null || (
+    echo "Creating a file with private settings, /root/<%= name %>.settings.private ,
+please fill it with proper keys and tokens"
+    echo '
+    export TWITTER_KEYS=
+    export CRUNCHBASE_KEY=
+    export GITHUB_TOKEN=
+    export GITHUB_USER=
+    export SLACK_CHANNEL=
+    export GITHUB_KEY=
+    ' > "<%= name %>.settings.private"
+
+)
 EOSSH
 
